language: node_js
node_js:
  - "6"

script:
  - npm build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: testproject.badrussell
  endpoint: www.testproject.badrussell.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  detect-encoding: true
