language: node_js
node_js:
  - "6"

script:
  - npm test
  - npm run build


deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "testproject.badrussell"
  skip_cleanup: true
  local-dir: dist
  upload-dir: $TRAVIS_BRANCH
  region: "us-east-1"
  acl: public_read

after_deploy:
  - aws configure set preview.cloudfront true
