language:
  - node_js
node_js:
  - "6"

env:
  - BUILD_ENV=test BUILDSHA=bash SHOULD_DEPLOY=true

install:
  - ./awscli-bundle/install -b ~/bin/aws
  - npm install

script:
  - npm test
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $TRAVIS_BRANCH
  skip_cleanup: true
  local-dir: dist
  upload-dir: $TRAVIS_COMMIT
  region: "us-east-1"
  acl: public_read
  on:
    all_branches: true

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-distribution --cli-input-json $(node cloudfront_distribution_json.js $TRAVIS_BRANCH $TRAVIS_COMMIT)
  - echo "done!"
