language:
  - node_js
node_js:
  - "6"

env:
  - BUILD_ENV=test BUILDSHA=bash SHOULD_DEPLOY=true

install:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

script:
  - npm test
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "testproject.badrussell"
  skip_cleanup: true
  local-dir: dist
  upload-dir: $TRAVIS_BRANCH
  region: "us-east-1"
  acl: public_read
  on:
    all_branches: true

after_deploy:
  - aws configure set preview.cloudfront true
  - aws s3 mb s3://sampleproject12345.badrussell
  - echo "done!"
